project:
  type: website
  resources:
    - docs-redirect.html
website:
  announcement:
    icon: baloon #megaphone
    dismissable: true
    content: "Welcome to the new hubverse site. If you have any comments, feel free to [provide feedback](https://github.com/hubverse-org/hubverse-site/issues/new)"
    type: info
    position: above-navbar
  favicon: logo/logo.png
  title: "hubverse"
  site-url: "https://hubverse.io"
  repo-url: "https://github.com/hubverse-org/hubverse-site"
  repo-actions: [edit, source, issue]
  navbar:
    search: true
    right:
      - text: "Home"
        href: index.qmd
      - text: "**Get Started**"
        menu:
        - icon: question-circle
          href: quickstart/index.qmd
        - icon: diagram-3
          href: quickstart/create.qmd
        - icon: file-earmark-arrow-up
          href: quickstart/submit.qmd
        - icon: graph-up
          href: quickstart/analyze.qmd
        - icon: braces
          href: quickstart/develop.qmd
        - "---"
        - icon: headset
          href: quickstart/support-consulting.md
        - icon: book
          text: "Documentation {{< fa arrow-up-right-from-square >}}"
          href: https://docs.hubverse.io/
      - text: "Tools"
        menu:
        - text: "Data Standards"
          icon: compass
          href: tools/data.qmd
        - text: "Software"
          icon: tools
          href: tools/software.qmd
        - text: "Dashboards"
          icon: speedometer
          href: tools/dashboards.qmd
        - text: "---"
        - text: "{{< fa book >}} Resources"
        - "terminology.qmd"
        - text: "Documentation {{< fa arrow-up-right-from-square >}}"
          href: https://docs.hubverse.io/
        - "CONTRIBUTING.md"
      - text: "About"
        menu:
        - icon: info-circle-fill
          href: "about.qmd"
        - text: "---"
        - text: "{{< fa people-line >}} Community"
        - text: "Get Involved"
          href: community/index.qmd
        - community/hubs.qmd
        - text: "Contributors"
          href: community/contributors.md
        - "contact.qmd"
        - text: "---"
        - text: "{{< fa book >}} Resources"
        - "terminology.qmd"
        - text: "Documentation {{< fa arrow-up-right-from-square >}}"
          href: https://docs.hubverse.io/
        - text: "Funding"
          href: "funding.md"
        - "CONTRIBUTING.md"
      - text: "{{< fa book >}} Docs {{< fa arrow-up-right-from-square >}}"
        href: https://docs.hubverse.io/
  page-footer:
    left:
      - icon: c-circle
        text: "Copyright 2025, Collaborative Modelling Consortium"
    right:
      - href: funding.md
      - href: contact.qmd
      - href: about.qmd
format:
  html:
    anchor-sections: true
    link-external-icon: true
    breadcrumbs: true
    theme:
      - litera
    css: styles.css
    toc: true
brand: brand/_brand.yml
resources:
 - logo/
 - includes/
