project:
  type: website
website:
  announcement:
    icon: cone-striped
    dismissable: true
    content: "This page is currently under construction"
    type: warning
    position: below-navbar
  favicon: logo/logo.png
  title: "The hubverse"
  site-path: "/hubverse-site/"
  repo-url: "https://github.com/hubverse-org/hubverse-site"
  repo-actions: [edit, source, issue]
  page-footer:
    left:
      - text: "Copyright 2025, Collaborative Modelling Consortium"
    right:
      - href: funding.md
      - href: contact.qmd
  navbar:
    search: true
    right:
      - text: "Home"
        href: index.qmd
      - text: "**Get Started**"
        menu:
        - quickstart/index.qmd
        - quickstart/create.qmd
        - quickstart/submit.qmd
        - quickstart/analyze.qmd
        - quickstart/develop.qmd
        - "---"
        - quickstart/support-consulting.md
      - text: "Tools"
        menu:
        - text: "Data Standards"
          href: tools/data.qmd
        - text: "Software"
          href: tools/software.qmd
        - text: "Dashboards"
          href: tools/dashboards.qmd
      - text: "About"
        menu:
        - text: "{{< fa people-pulling >}} Community"
        - text: "Get Involved"
          href: community/index.qmd
        - community/hubs.qmd
        - text: "Contributors"
          href: community/contributors.md
        - text: "---"
        - text: "{{< fa book >}} Resources"
        - text: "Funding"
          href: "funding.md"
        - "terminology.qmd"
        - text: "User Guide (external) {{< fa arrow-up-right-from-square >}}"
          href: https://hubverse.io/
format:
  html:
    anchor-sections: true
    link-external-icon: true
    breadcrumbs: true
    theme:
      - litera
      # - brand
    css: styles.css
    toc: true
brand: brand/_brand.yml
resources: 
 - logo/
 - includes/
