project:
  type: website
website:
  favicon: logo/logo.png
  title: "The Hubverse"
  site-path: "/hubverse-site/"
  repo-url: "https://github.com/hubverse-org/hubverse-site"
  repo-actions: [edit, source, issue]
  navbar:
    search: true
    right:
      - text: "Home"
        href: index.qmd
      - text: "**Get Started**"
        menu:
        - quickstart/index.qmd
        - quickstart/create.qmd
        - quickstart/submit.qmd
        - quickstart/analyze.qmd
        - "---"
        - quickstart/support-consulting.md
      - text: "Tools"
        menu:
        - text: "Data Standards"
          href: tools/data.qmd
        - text: "Software"
          href: tools/software.qmd
        - text: "Dashboards"
          href: tools/dashboards.qmd
      - text: "Community Support"
        menu:
        - community/index.qmd
        - community/hubs.qmd
        - text: "User Guide (external)"
          href: https://hubverse.io/
        - text: "Contributors"
          href: community/contributors.md
format:
  html:
    anchor-sections: true
    link-external-icon: true
    breadcrumbs: true
    theme:
      - litera
      # - brand
    css: styles.css
    toc: true
brand: brand/_brand.yml
resources: 
 - logo/
 - includes/
