
::::{.callout-important}

You should contact the hubverse administrator before submitting your model to a
hub. They will ask you to provide metadata for your model.

::::

[{{< fa box-open >}} hubValidations](https://hubverse-org.github.io/hubValidations){.btn .btn-outline-info .ms-auto}

Useful tools are available in the **hubValidations** R package.

 - Create a **submission template** with [`hubValidations::submission_tmpl()`](https://hubverse-org.github.io/hubValidations/reference/submission_tmpl.html)
 - **Validate** your submission with [`hubValidaitons::validate_submission()`](https://hubverse-org.github.io/hubValidations/reference/validate_submission.html)

[{{< fa book >}} Model metadata](https://docs.hubverse.io/en/latest/user-guide/model-metadata.html){.btn .btn-outline-dark .ms-auto}
[{{< fa book >}} Writing model output to a hub](https://docs.hubverse.io/en/latest/user-guide/model-output.html#writing-model-output-to-a-hub){.btn .btn-outline-dark .ms-auto}
[{{< fa file-circle-check >}} Validate model submission](https://hubverse-org.github.io/hubValidations/articles/validate-submission.html){.btn .btn-outline-dark .ms-auto}

::::{.callout-tip collapse="true"}

#### TIP: A lightweight way to clone a hub

A modelling hub hosted on GitHub will grow in size over time and it often can
take up several hundreds of megabytes or several gigabytes of space. **To reduce
the size of a hub on your local machine**, you can use [git sparse
checkout](https://git-scm.com/docs/git-sparse-checkout). Here's an example
using the FluSight Forecast Hub, but only checking out the model outputs for 
the `FluSight-baseline` model:

```bash
git init FluSight-Forecast-Hub
cd FluSight-Forecast-Hub
git remote add origin https://github.com/cdcepi/FluSight-Forecast-Hub.git
git sparse-checkout set --no-cone '/*' 'model-output/FluSight-baseline*' '!/model-output'
git pull origin main
```

Now when you run `git status`, you will see that you only have a fraction of the files on your local machine:

```bash
git status
# On branch main
# You are in a sparse checkout with 14% of tracked files present.
#
# nothing to commit, working tree clean
```

::::
