---
title: "Community"
---

![
The Consortium of Infectious Disease Modeling Hubs (June 2023). Back row (L-R): Kath Sherratt, Lucie Contamin, Nick Reich, Matthew Biggerstaff, Rebecca Borchering, Martha Zorn\
Front row (L-R): Anna Krystalli, Evan Ray
](/includes/img/hubverse-retreat-2023.jpg){alt='Photo of smiling and laughing people standing in the sunshine in front of a lawn with trees and a brick building in the background.'}

## Get Involved

### Mailing list

This group is used to announce new features in the hubverse to the user
community. If you would like to become a hubverse community member, go to
[the hubverse mailing list](https://groups.io/g/hubverse) and click on the
**+Apply for Membership in this group** at the bottom left-hand side of the
page.

The Consortium of Infectious Disease Modeling Hubs built the hubverse
collaboratively, and we benefit from your contributions.

### Monthly community meetings

If you are using the hubverse or are interested in using the hubverse in the
future, please consider joining our monthly community hubverse meetings.
During these meetings, we provide general updates from a broad mix of
developers and public health representatives running hubs or thinking about
starting to run hubs.

To join the community hubverse meeting, please [send an email to the hubverse
group](mailto:hubverse+owner@groups.io), including your name,
email, and a few sentences about how you would like to use the hubverse.


## Use and test our software and tools

The hubverse was created for teams to develop and set up collaborative modeling hubs easily, and we benefit from having groups use these tools and tell us about them.

### File issues

Let us know if something is not working for you or if something could improve. This could be a bug in the code, a case where the tools are not appropriate for your use case, a problem with the documentation, or something else. Issues can be filed in any of [the hubverse repositories](https://github.com/hubverse-org). You are also welcome to [join the discussion](https://github.com/orgs/hubverse-org/discussions) on any existing issue in any of the hubverse repositories.

### Contribute code

If you want to contribute to *the hubverse*, please see the [guidelines for contributing](https://hubverse-org.github.io/hubUtils/CONTRIBUTING.html).

### Join the development team

If you are an experienced programmer interested in joining the development team, we have "development meetings" on all Wednesdays except the first Wednesday of the month. These meetings are for technical updates and discussions about ongoing development tasks.

To join the development team, please [send an email to the hubverse group](mailto:hubverse+owner@groups.io), including your name, email, and a few sentences about what you can contribute to the development team.

## Governance

The governing body of the [Consortium of Infectious Disease Modeling Hubs](/about.qmd) is the Coding Council, which comprises of any community member attending one of the periodic virtual meetings. This council generally serves as a deliberative body, discussing and setting directions for new conceptual and software development. Typically, decisions about design and prioritization are made through consensus at the Coding Council level. If differences cannot be solved by consensus, then decisions are passed to the Steering Committee, which comprises three members. Members of the Steering Committee serve one-year terms, with elections occurring in July of each calendar year. Members of the Coding Council may nominate themselves or others to serve on the Steering Committee, and a closed-ballot vote is taken if more than three individuals are nominated. The highest three vote-getters serve on the council.

On July 10, 2024, the following members of the steering committee were elected:

- Evan Ray, US Forecast Hub
- Lucie Contamin, University of Pittsburgh, MIDAS
- Anna Krystalli, R-RSE

