---
title: '<i class="bi bi-diagram-3"></i> Create a hub'
pagetitle: "Create a hub"
---

## Determine what model output you want to collect

You need to answer a few questions first:

1. What quantities do you want to collect? These are your **modeling targets**
2. What variables do you want to use for modeling? These are your **modeling task IDs**
3. What is the modeling horizon (if any)?
4. What kind of estimates do you expect to represent the value of the modeling target (e.g. quantile and mean values)? These are **output types**.
5. How often do you want to take submissions? your **modeling rounds**

By answering these questions, you will be able to determine your **modeling tasks**.
A modeling task focuses on a single target and is made up of a unique
combination of variables used for modeling and the output types. These variables
are collectively known as **task IDs**.

[{{< fa compass-drafting >}} Follow the quickstart guide](https://docs.hubverse.io/en/latest/quickstart-hub-admin/intro.html){.btn .btn-outline-dark .ms-auto}
[{{< fa book >}} Hub configuration files](https://docs.hubverse.io/en/latest/user-guide/hub-config.html){.btn .btn-outline-dark .ms-auto}

## Create your hub

{{< include /_snippets/create.qmd >}}

## Important packages

As an administrator, you might want to use these tools to help you administer
your hub.

 - [hubAdmin](https://hubverse-org.github.io/hubAdmin) provides tools for you to create a new hub
 - [hubCI](https://hubverse-org.github.io/hubCI) allows you to set up automated check for your hub on github

:::: {.page-nav}
::: {.prev-page}
[‹](/quickstart/index.qmd){.prev-arrow}

[Previous](/quickstart/index.qmd){.prev-label}

[**What is a modeling hub?**](/quickstart/index.qmd){.prev-title}
:::

::: {.next-page}
[Next](/quickstart/submit.qmd){.next-label}

[›](/quickstart/submit.qmd){.next-arrow}

[**Submit model output**](/quickstart/submit.qmd){.next-title}
:::
::::

